Telemetry configurable Added
gouravmore/tn-language-lab pull request #27
Opened 2023-08-02 14:48 UTC by ajinkyapandetekdi

2023-08-02 15:03 UTC, gouravmore commented on src/environments/environment.ts
> +  telemetry_mode: 'ET', // can assign any variables as follows: Essential-Telemetry = ET, Normal-Telemetry = NT, and Detailed-Telemetry = DT.
Make the default as DT for now.

2023-08-02 15:10 UTC, gouravmore requested changes

2023-08-02 15:10 UTC, gouravmore commented on src/app/login/login.component.ts
> +            'ET'
all the errors should Detailed-Telemetry = DT

2023-08-02 15:10 UTC, gouravmore commented on src/app/telemetry.service.ts
> +    if (
Write one common function which will return true/false

2023-08-02 15:10 UTC, gouravmore commented on src/app/telemetry.service.ts
> +      (this.TELEMETRY_MODE === 'ET' && currentMode === 'ET') ||
Write one common function which will return true/false

2023-08-02 15:10 UTC, gouravmore commented on src/app/views/pages/level/level.component.html
> +            <button class="px-3 py-2 rounded bg-primary border-0 text-white fs-10 mt-1" (click)="telemetryService.interact('logout', 'level','ET'); logout()">Logout</button>
this should be NT

2023-08-02 15:10 UTC, gouravmore commented on src/assets/games/index.html
> +<!doctype html><html lang="en"><head><meta charset="utf-8"/><link rel="icon" href="./logo.png"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="theme-color" content="#
Are there any changes in the games?

2023-08-02 15:10 UTC, gouravmore commented on src/assets/sb-all/static/js/main.7c446933.js.LICENSE.txt
> +/*
Is this changes required for this PR?

2023-08-02 15:10 UTC, gouravmore commented on src/environments/environment.prod.ts
> +  telemetry_mode: 'ET' // can assign any variables as follows: Essential-Telemetry = ET, Normal-Telemetry = NT, and Detailed-Telemetry = DT.
Default should be DT

2023-08-03 06:35 UTC, ajinkyapandetekdi commented on src/assets/games/index.html
> +<!doctype html><html lang="en"><head><meta charset="utf-8"/><link rel="icon" href="./logo.png"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="theme-color" content="#
I didn't change anything in those files, but I got those files after taking a pull.

2023-08-03 06:38 UTC, ajinkyapandetekdi commented on src/assets/sb-all/static/js/main.7c446933.js.LICENSE.txt
> +/*
i took pull then it came to my code. This is only txt file

2023-08-03 17:41 UTC, closed without merging