Buddy login functionality
gouravmore/tn-language-lab pull request #31
Opened 2023-08-08 09:03 UTC by sonaliTekdi

2023-08-08 10:21 UTC, gouravmore requested changes

2023-08-08 11:00 UTC, sonaliTekdi commented on src/app/buddy-login/buddy-login.component.ts
> +    if(this.userService.getUser().emis_username===this.email)
Added space

2023-08-08 11:03 UTC, sonaliTekdi commented on src/app/telemetry.service.ts
> +    // localStorage.setItem("UID_1",this.userService.getUser().emis_username)
removed

2023-08-08 11:04 UTC, sonaliTekdi commented on src/app/buddy-login/buddy-login.component.ts
> +          // alert(data.message)
Removed comments

2023-08-08 11:19 UTC, sonaliTekdi commented on src/app/user/user.service.ts
> +  buddyUserData1: any;
I have changes two variable into one variable buddyUserData for stored and return token2

2023-08-08 11:19 UTC, sonaliTekdi commented on src/app/user/user.service.ts
> +      this.buddyUserData2 = jwt_decode(token2);
I have added variable as buddyUserData

2023-08-08 11:21 UTC, sonaliTekdi commented on src/app/telemetry.service.ts
> +        uid: isBuddyLogin==='true'? this.userService.getUser().emis_username+" / "+this.userService.getBuddyUser().emis_username : this.userService.getUser().emis_username || 'anonymous',
Done

2023-08-08 11:22 UTC, sonaliTekdi commented on src/app/auth.service.ts
> +    localStorage.removeItem('buddyToken');
Removed

2023-08-08 11:23 UTC, sonaliTekdi commented on src/app/auth.service.ts
> +    localStorage.removeItem('BuddyLogin');
Removed dublicate

2023-08-08 11:27 UTC, sonaliTekdi commented on src/app/auth.service.ts
> +  buddyLogin(email: string, password: string): Observable<any> {
Removed dublicate code

2023-08-08 11:30 UTC, sonaliTekdi commented on src/app/buddy-login/buddy-login.component.ts
> +    this.telemetryService.impression('Login', '/login', 'ET');
Added

2023-08-08 11:31 UTC, sonaliTekdi commented on src/app/login/login.component.ts
> +  isBuddyLogin = localStorage.getItem('BuddyLogin')
Removed unwanted localstorage code

2023-08-08 11:34 UTC, sonaliTekdi commented on src/app/telemetry.service.ts
> +  const isBuddyLogin = localStorage.getItem('BuddyLogin')
We are using it.

2023-08-09 06:15 UTC, sonaliTekdi commented on src/app/auth.service.ts
> +    localStorage.removeItem('buddyToken');
If I removed it then buddyToken not  removed form local storage that's why I leave it as it is

2023-08-09 06:16 UTC, sonaliTekdi commented on src/app/auth.service.ts
> +    localStorage.removeItem('BuddyLogin');
BuddyLogin and BuddyToken both are different so I leave it as it is.

2023-08-09 06:18 UTC, sonaliTekdi commented on src/app/login/login.component.ts
> +  isBuddyLogin = localStorage.getItem('BuddyLogin')
I have set it for to get Buddy login userid and username from localstorage.so I leave as it is

2023-08-09 11:05 UTC, merged